#ifndef LEVERBOARDHARDWARE_H_INCLUDED
#define LEVERBOARDHARDWARE_H_INCLUDED

// GPIOs
#define PORT_LEDS PORTA
#define TRISTATE_LEDS DDRA
#define PIN_LED0 0
#define PIN_LED1 1
#define PIN_LED2 2
#define PIN_LED3 3

#define PORT_PIEZO PORTA
#define TRISTATE_PIEZO DDRA
#define PIN_PIEZO 4

#define PORT_ENABLE_DRIVER PORTA
#define TRISTATE_ENABLE_DRIVER DDRA
#define PIN_ENABLE_DRIVER 5

#endif // LEVERBOARDHARDWARE_H_INCLUDED
